spring.application.name=PaymentServiceNov
razorpay.key.id=rzp_test_jBZLTMDMLiET59
razorpay.key.secret=TItrErDIGF4N1vNTINOcbzWt

eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
server.port=9000